### ISSUE TITLE
Bible in a public GitHub repo

### ISSUE THREAD

**Issue by JESUSrosetolife** [barnhill/SimpleBible#5]
> Proverbs 25:2 **It is the glory of God to conceal a matter**, But the glory of kings is to search out a matter.

**Comment by barnhill** [comment]
Yikes that's not supposed to be there as it's not used in any code here.

**Comment by barnhill** [comment]
removed it https://github.com/barnhill/Bible/commit/ca2ddcf6d29e78df59a835b4076605a919cdf957
